### ISSUE TITLE
Fatal error message comes out when in .git

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/bash-config#15]
```
lion [ .git@ ] $ 
fatal: This operation must be run in a work tree
fatal: This operation must be run in a work tree
```

**Comment by MingcongBai** [comment]
@Artoria2e5 Will a simple silencer suffice here?

**Comment by Artoria2e5** [comment]
yes

**Comment by MingcongBai** [comment]
Cool,

**Comment by LionNatsu** [comment]
Shall we closed this? (Solved?)

**Comment by Icenowy** [comment]
@LionNatsu Nope.

icenowy@x220i [ .git@staging ] $ 
fatal: This operation must be run in a work tree
fatal: This operation must be run in a work tree
