### ISSUE TITLE
Add shopt

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/bash-config#6]
shopt enables some features and sometimes make life easier.

However, it seems that they should be included in `/etc/skel`.

In Cygwin:
```Bash
#
# Use case-insensitive filename globbing
shopt -s nocaseglob
#
# Make bash append rather than overwrite the history on disk
shopt -s histappend
#
# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell
```

In ABS: http://www.tldp.org/LDP/abs/html/sample-bashrc.html

**Comment by Arthur2e5** [comment]
Noooooooooooooooo! I Said skel!

**Comment by Arthur2e5** [comment]
OK, fine with rc.

**Comment by MingcongBai** [comment]
I though you guessed skel. But I thought bashrc declares the contents that
all users using Bash will use.
2015年6月23日 下午4:22于 "Mingye Wang" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
Alright...
2015年6月23日 下午4:28于 "Mingye Wang" <notifications@github.com>写道：
