### ISSUE TITLE
Line wrapping issue with long commands

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/bash-config#8]
A sample of output...

er_0.37-0.tar.xzin@master ] # wget http://repo.anthonos.org/os3-next/os3-ab/c/cgmanag

**Comment by MingcongBai** [comment]
@Arthur2e5 Currently simply input of command won't cause any problem (master checkout), but scrolling back in command history will still cause a faulty line wrap.

**Comment by biergaizi** [comment]
This is a common problem in Unix shell, which is unsolvable. Especially when the command is very long, or contains Unicode characters.

**Comment by Arthur2e5** [comment]
Requesting test cases:
```Bash
# human-input
hand 'echo '
hand ALT50(
hand ENTER
hand UP
hand PS1='\

**Comment by biergaizi** [comment]
It's also related to the terminal emulators you use.

**Comment by MingcongBai** [comment]
```
jeffbai [ ~ ] $ ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
bash: ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss: 未找到命令...
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
bash: ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss: 未找到命令...
jeffbai [ ~ ] ? PS1='\w$ '
~$ ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
```
Ah hah... @Arthur2e5

**Comment by Arthur2e5** [comment]
http://lists.gnu.org/archive/html/bug-bash/2015-08/msg00027.html points out that the `\[` and `\]` in `PS1` are actually `RL_PROMPT_START_IGNORE` (\001) and `RL_PROMPT_END_IGNORE`
(\002).

So to fix this, we wrap the colors manually like `$'\1'COLOR$'\2'` in `_ret_prompt()`.

**Comment by MingcongBai** [comment]
> So to fix this, we wrap the colors manually like $\1\e[1;31m\2' in _ret_prompt().

Sounds like a rebuild on color functions?

**Comment by Arthur2e5** [comment]
@MingcongBai OR a rebuild on color variables.

**Comment by Arthur2e5** [comment]
Well, Bai, which one do you think is better? Simply changing the variables IMO would be better, since it saves time of authors of other scripts and it won't do anything weird when printed to the terminal.

**Comment by MingcongBai** [comment]
@Arthur2e5 Considering it is already doing so. Yes, I will go with your idea.

**Comment by Arthur2e5** [comment]
GitHub is magical. By saying `fixed #8` in the commit title I closed the issue.

**Comment by MingcongBai** [comment]
Ignorant...
2015年8月10日 上午11:10于 "Mingye Wang" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
Gone worse after 05f9968d20f6a14ecb48a7979f8cae4977a0a4a0.

**Comment by Arthur2e5** [comment]
Verifies that `echo -e` doesn't accept `\1`, but `\01`. It's just more C-lish with those octals.

**Comment by Arthur2e5** [comment]
Sadly we still have to use `\[` and `\]` if they are inside `PS1`, and use the raw RL stuffs when it comes from a command substitution. Additional discussion on how we should handle those variables should be performed.

VCS functions may be affected now.

**Comment by MingcongBai** [comment]
@Arthur2e5 if without `\` it means more trouble with line wrapping (up to the width reading issue).

**Comment by Arthur2e5** [comment]
And @biergaizi, I believe readline would still provide ways for most of the use cases. Well, I admit that the problem with some Unicode characters that they may appear at half, one or multiple `em`s still exist, but with CJK and latin characters we would be just fine.

@MingcongBai reported the latest fix to be working, but VCS functions still need checks (and yet I believe we should not arrange it like this) so not closed.

**Comment by MingcongBai** [comment]
And check this out. @Arthur2e5 

```
jeffbai [ bash-config@master ] $ sudo su
[sudo] jeffbai, your password please: 
jeffbai [ bash-config@master ] \[! git add --a^C
jeffbai [ bash-config@master ] $ sudo su
[sudo] jeffbai, your password please: 
jeffbai [ bash-config@master ] \[! git add --all bashrc
```

**Comment by Arthur2e5** [comment]
Ah, ha! duplicating `\[` in `_ret_prompt`. That's my concern for those characters built into the whole string in the first place.

**Comment by MingcongBai** [comment]
@Arthur2e5 More like a careless mistake to me.
